name: Telegram-WOL
description:  Wake up your devices from anywhere
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  teledart: ^0.3.4
  intl: ^0.18.0
  wake_on_lan: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
